# Generated by Django 6.0 on 2025-12-31 08:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClothingItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("haut", "Haut"),
                            ("bas", "Bas"),
                            ("veste", "Veste"),
                            ("chaussures", "Chaussures"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("color", models.CharField(max_length=50, verbose_name="Couleur")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="clothing_photos/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                        verbose_name="Photo",
                    ),
                ),
                (
                    "deposit_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date de dépôt"
                    ),
                ),
                ("location", models.CharField(max_length=100, verbose_name="Lieu")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("au_travail", "Au travail"),
                            ("recupere", "Récupéré"),
                            ("perdu", "Perdu"),
                        ],
                        default="au_travail",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clothing_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vêtement",
                "verbose_name_plural": "Vêtements",
                "ordering": ["-deposit_date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.URLField(blank=True, max_length=500, verbose_name="Avatar"),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="google, github, strava",
                        max_length=50,
                        verbose_name="Fournisseur OAuth",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil utilisateur",
                "verbose_name_plural": "Profils utilisateur",
            },
        ),
    ]
