#!/bin/bash
# Quick Start Guide - Tester l'authentification

echo "======================================================================"
echo "GUIDE DE DÉMARRAGE RAPIDE - AUTHENTICATION"
echo "======================================================================"
echo ""
echo "Ce script vous guide pour tester l'authentification locale."
echo ""

# Vérifier que le serveur n'est pas déjà lancé
if lsof -Pi :8000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo "✅ Le serveur Django est déjà en cours d'exécution sur le port 8000"
    echo ""
else
    echo "ℹ️  Le serveur n'est pas encore démarré."
    echo ""
    echo "Pour démarrer le serveur, exécutez dans un terminal:"
    echo "  uv run python manage.py runserver"
    echo ""
fi

echo "======================================================================"
echo "ÉTAPE 1: Créer un superuser"
echo "======================================================================"
echo ""
echo "Exécutez la commande suivante pour créer un compte administrateur:"
echo ""
echo "  uv run python manage.py createsuperuser"
echo ""
echo "Puis entrez:"
echo "  - Email: admin@example.com (ou votre email)"
echo "  - Password: (un mot de passe sécurisé)"
echo ""
read -p "Appuyez sur Entrée quand c'est fait..."
echo ""

echo "======================================================================"
echo "ÉTAPE 2: Tester les URLs d'authentification"
echo "======================================================================"
echo ""
echo "Ouvrez votre navigateur et testez ces URLs:"
echo ""
echo "1. Login:      http://localhost:8000/accounts/login/"
echo "   → Connectez-vous avec le superuser créé"
echo ""
echo "2. Signup:     http://localhost:8000/accounts/signup/"
echo "   → Créez un nouveau compte utilisateur"
echo ""
echo "3. Admin:      http://localhost:8000/admin/"
echo "   → Interface d'administration Django"
echo ""
echo "4. Logout:     http://localhost:8000/accounts/logout/"
echo "   → Déconnexion"
echo ""

echo "======================================================================"
echo "ÉTAPE 3: Vérifier les fonctionnalités"
echo "======================================================================"
echo ""
echo "Testez que:"
echo "  ✓ La page de login affiche les boutons OAuth (Google, GitHub, Strava)"
echo "  ✓ Le formulaire de connexion locale fonctionne"
echo "  ✓ Vous pouvez créer un nouveau compte"
echo "  ✓ La déconnexion fonctionne correctement"
echo ""

echo "======================================================================"
echo "ÉTAPE 4 (OPTIONNELLE): Configurer OAuth"
echo "======================================================================"
echo ""
echo "Pour activer l'authentification OAuth, consultez:"
echo "  📄 docs/OAUTH_SETUP.md"
echo ""
echo "Providers disponibles:"
echo "  • Google OAuth 2.0"
echo "  • GitHub OAuth"
echo "  • Strava OAuth"
echo ""

echo "======================================================================"
echo "TESTS AUTOMATISÉS"
echo "======================================================================"
echo ""
echo "Pour relancer les tests d'authentification:"
echo "  uv run python manage.py test clothing.test_auth"
echo ""
echo "Pour tous les tests:"
echo "  uv run python manage.py test clothing"
echo ""

echo "======================================================================"
echo "DOCUMENTATION COMPLÈTE"
echo "======================================================================"
echo ""
echo "Consultez CHECKPOINT_TASK_4.md pour:"
echo "  • Statut détaillé de la configuration"
echo "  • Liste complète des tests passés"
echo "  • Guide de vérification manuelle"
echo "  • Instructions OAuth"
echo ""

echo "======================================================================"
echo "✅ Tâche 4 complétée!"
echo "======================================================================"
echo ""
echo "Prochaine étape: Tâche 5 - Vues et templates de l'application"
echo ""
